# Your project's server will run on localhost:xxxx at this port
PORT: 3000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dest"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
  data:
    - "src/html/data/global.json"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/bootstrap/scss"
  # Paths to JavaScript libraries, which are compined into one file
